### ISSUE TITLE
Doesn't work with Midtown Madness and MCI_PAUSE doesn't work

### ISSUE THREAD

**Issue by BEENNath58** [dippy-dipper/cdaudio-winmm#7] opened 2021-02-10 11:04 UTC
When I launch Midtown Madness, the game gives out an error while loading the MCI driver. 
![mmmcierror](https://user-images.githubusercontent.com/64649734/107501251-32311300-6bbd-11eb-8700-0e5e7ca70b1e.png)

Another thing I noticed is that the music doesn't pause on games like Rebel Moon Rising or Codename Eagle.

**Comment by dippy-dipper** [comment] 2021-02-12 16:38
**For the Midtown Madness case:**

Midtown Madness uses the MCI API to play videos in addition to music. The ogg-winmm based wrapper is not equipped to handle pass-through for other devices and intercepts all calls made to the MCI API. This means that the game is unable to play videos using MCI and this also results in the error message.

The short answer is that the current cdaudio-winmm wrapper is not build to handle this situation and will fail miserably. The way to do this in the future would be a more intelligent winmm wrapper that has a pass through for video, etc. This can be done using a ASM jump for all the winmm functions that are meant to be passed to the real winmm.dll.

The second issue with Midtown Madness and the cdaudio-winmm wrapper is that later on when the game tries to play a cdaudio track it queries for the track position and instead of receiving the answer that it expect it always receives "1". This is something I need to look at in the code as it is currently hard coded to return "2001" milliseconds or the first track "1".

**Comment by dippy-dipper** [comment] 2021-02-12 21:18
I was a bit too hasty jumping into conclusions. I was comparing the behavior to the ogg-winmm wrapper and noticed the difference in the response to the status mode query. However this appears to not be important. I don't think the code revision hurts though.

I noticed that you can still play the music manually when in the driving phase of the game by pressing "2" on the keyboard and then toggling the music on/off using the "3" key and change the track using "4" and "5" keys. Perhaps not ideal but better than nothing.

And finally there is this project that could fix these issues better:
https://github.com/0x1F9F1/Open1560

**Comment by dippy-dipper** [comment] 2021-02-12 22:00
**For the Rebel Moon Rising case:**

I tested the Shareware version which also supports cdaudio tracks. Here I saw no references to MCI_PAUSE call in the winmm.log. In the main menu of the game if one uses alt+tab the music continues playing. However if one alt tabs later on in the actual gameplay part the music does stop and begins again from the beginning of the track with MCI_PLAY when returning to the game. In this case a simple MCI_STOP / MCI_PLAY method is used. This appears to be the behavior of the game even when run without mci wrappers using a music cd in the CD-drive.

**Comment by dippy-dipper** [comment] 2021-02-13 14:47
**Regarding Codename Eagle Nation:**

No sign of MCI_PAUSE in the winmm.log here either. Basically the game seems to be programmed in a way that it does not stop or pause the music playback when the game is alt tabbed. The wrapper can not add a pause function to the game if it was never there in the first place.

**Comment by BEENNath58** [comment] 2021-02-13 18:07
> **For the Rebel Moon Rising case:**
> 
> I tested the Shareware version which also supports cdaudio tracks. Here I saw no references to MCI_PAUSE call in the winmm.log. In the main menu of the game if one uses alt+tab the music continues playing. However if one alt tabs later on in the actual gameplay part the music does stop and begins again from the beginning of the track with MCI_PLAY when returning to the game. In this case a simple MCI_STOP / MCI_PLAY method is used. This appears to be the behaviour of the game even when run without mci wrappers using a music cd in the CD-drive.

My bad, I tried out the games on a Windows 98 PC, and the same behaviour exists on both the system. It is a mistake from my side, I confused some other games with these two. 

Regarding Midtown Madness, I actually enjoy playing the original game over some fan-made remasters/patches, so I wanted to test if this one would fix the bug where the game wouldn't play the music after exiting a race. Turns out, the problem isn't probably lying in winmm, but instead somewhere in the game, this thing occurs on every winmm wrapper I tested out. For now, I think I will stick with using Open1560, since it has this fixed.

**Comment by dippy-dipper** [comment] 2021-02-14 14:26
> Turns out, the problem isn't probably lying in winmm, but instead somewhere in the game, this thing occurs on every winmm wrapper I tested out. For now, I think I will stick with using Open1560, since it has this fixed.

Yes, the Midtown Madness music is probably fixed in Open1560 here:
https://github.com/0x1F9F1/Open1560/issues/45

So it seems like the game is making assumptions about the device names based on DirectSound and the WinMM mixers. This probably worked on older Windows versions but for example starting with Windows Vista the Mixer controls were completely revised. There is also a Microsoft ACT shim called "HardwareAudioMixer" but turning this on crashes the game at startup.

**Comment by 0x1F9F1** [comment] 2021-02-16 14:03
MM1's music playback depends on whether or not it thinks you have inserted the game CD or some other audio CD (it does this by checking if the CD contains a file named CDID.txt). It will only auto-play music (including in the menu) when it thinks you are using the game CD. (Open1560 lets you get around this by passing the `-cdid` cmd param).
The main issues vanilla MM1/winmm have are:
* MCI_STATUS after MCI_STOP now returns the start of the track, instead of the middle, which breaks pausing/unpausing
* MCI_NOTIFY no longer works, so after a track is finished it won't play the next one

Also fwiw 0x1F9F1/Open1560#45 was to fix the mixer* apis, not the mci* ones

**Comment by dippy-dipper** [comment] 2021-02-16 19:33
OK, it was a user error on my part that confused the situation. I have two DVD drives and once I disabled the second drive and put the disc in the first one (and rebooted) the music plays in the menu screens even with the original executable. I will run some more tests now that I have a proper setup.

**Comment by BEENNath58** [comment] 2021-02-17 04:38
> OK, it was a user error on my part that confused the situation. I have two DVD drives and once I disabled the second drive and put the disc in the first one (and rebooted) the music plays in the menu screens even with the original executable. I will run some more tests now that I have a proper setup.

The last reply confused me, but now since it's working, you could see what happens after you exit the race.

**Comment by BEENNath58** [comment] 2021-02-17 04:46
The other thing I noticed is that, when I play the game on a different output device rather than what is selected, the CD audio and effect streams are split into multiple output channels. For example, the menu for the game provides me with 'Realtek Output audio', 'USB audio device', 'Primary Audio Device', 'NVIDIA HD Audio'. If I use the USB Audio device as my output device, but the menu is selected with "Realtek Output Device', then the game will output only the sound effects and not the CD Audio even if it is selected. And when I exit the race with this setting, the sound effects suprisingly seem to work fine. 
Now if I choose 'USB Audio Device' from the menu, the effects and CD Audio will work together, but when I exit the game, none of the sound will output.

**Comment by dippy-dipper** [comment] 2021-02-18 17:16
I see the issue with changing the audio device now. I have two options and if I leave it set to the default Realtek device the music and sounds seem to work fine. However if I select the primary audio device all sounds and music is muted when exiting a race.

Setting the sound quality to low together with the primary audio device results in a game crash and I had to delete "\players\player0.cfg" to get the game running again.

Of course with the Open1560 executable I can use either output device without issues.

As for cdaudio-winmm it fails to work with the original game executable. What happens is that the music keeps "pausing" unless the mouse cursor is moved all the time. This is difficult to notice when using a real cdaudio disc but it's very noticeable when .wav or .mp3 files are used. I thought the game is suspending the threads or the player application but I am not sure. Whatever is happening the cdaudio-winmm wrapper is unusable with the original game executable at this point. Again things seem to work fine with Open1560.

The only way I got the emulated music working with the original game was with the ogg-winmm wrapper and ripped audio tracks in .ogg format.

**Comment by dippy-dipper** [comment] 2021-02-19 18:17
Regarding cdaudio-winmm and the Open1560 combination:

Using a real disc in the drive and cdaudio-winmm to fix the track repeats seemed to work fine but there is a problem. That is when you click on "Restart Race" the cdaudio player breaks. It seems to work with .wav/.mp3 tracks so the issue is either with the cdaudio device or the code that is handling the cdaudio playback. Possibly it's an issue with device latency. Wav/mp3 tracks play instantly but the real disc needs some delay to wait for it to spin-up, etc...

So it looks like you need to use cdaudio-wimm together with ripped .wav or .mp3 tracks or alternatively use ogg-wimm and ripped .ogg tracks.

**Comment by dippy-dipper** [comment] 2021-02-20 17:20
Uploaded 0.4.0.2-beta which should work with MidtownMadness Open1560 using the original disc in the CD drive and playing music from it. The issue was the incomplete MCI_STATUS_POSITION for current track in TMSF format emulation.

**Comment by BEENNath58** [comment] 2021-02-22 17:07
> I see the issue with changing the audio device now. I have two options and if I leave it set to the default Realtek device the music and sounds seem to work fine. However if I select the primary audio device all sounds and music is muted when exiting a race.
> 
> Setting the sound quality to low together with the primary audio device results in a game crash and I had to delete "\players\player0.cfg" to get the game running again.
> 
> Of course with the Open1560 executable I can use either output device without issues.
> 
> As for cdaudio-winmm it fails to work with the original game executable. What happens is that the music keeps "pausing" unless the mouse cursor is moved all the time. This is difficult to notice when using a real cdaudio disc but it's very noticeable when .wav or .mp3 files are used. I thought the game is suspending the threads or the player application but I am not sure. Whatever is happening the cdaudio-winmm wrapper is unusable with the original game executable at this point. Again things seem to work fine with Open1560.
> 
> The only way I got the emulated music working with the original game was with the ogg-winmm wrapper and ripped audio tracks in .ogg format. https://github.com/dippy-dipper/ogg-winmm

I will check again for my Realtek device. I have 5 options in the menu and as far as I remember, the Realtek audio has the same effect as you get with Primary audio device, the sound and music is muted.

**Comment by 0x1F9F1** [comment] 2021-02-22 18:32
> I rechecked this time with my speaker configuration, and things got worse. This time, if I exit the race, the sound wo't work as usual, but if I go to the menu and change the sound device and revert back to the one I am not using, the sound is still missing.
> 
> Between all of this I need to mention I have installed the Windows XP patch, since that removes the DRM. There may also be a problem by this patch but I am not quite sure.
> 
> Edit: I decided to try, for once, disable all other sound hardware and run the game with 2 options, Realtek Speaker and Primary Sound Driver. Turns out, it work fine then.

Vanilla MM1 has problems selecting the right audio device. Try using Open1560, and if it is still broken left me know.

**Comment by dippy-dipper** [comment] 2021-02-22 20:50
Regarding the issue with cdaudio-winmm and the original game executable I found that the Microsoft ACT shim **LowerThreadPriority** allows the music to play without pausing.

**Comment by 0x1F9F1** [comment] 2021-02-22 20:56
Vanilla MM1 pins the game to 1 core, which can cause issues with background threads. Lowering the priority of the main thread gives the other threads more of a chance to run. As with all problems, the answer is: use Open1560 :)

**Comment by dippy-dipper** [comment] 2021-02-22 21:53
> Vanilla MM1 pins the game to 1 core, which can cause issues with background threads. Lowering the priority of the main thread gives the other threads more of a chance to run. As with all problems, the answer is: use Open1560 :)

I agree but it was good for me to know that games running in high priority can hang the cdaudio player. Instead of a compatibility shim one could also just lower the games priority or increase the players priority in the task manager. Maybe I should hard code in a high priority for the cdaudio player in case there are other games with a similar issue...

**Comment by BEENNath58** [comment] 2021-02-23 05:25
> > I rechecked this time with my speaker configuration, and things got worse. This time, if I exit the race, the sound wo't work as usual, but if I go to the menu and change the sound device and revert back to the one I am not using, the sound is still missing.
> > Between all of this I need to mention I have installed the Windows XP patch, since that removes the DRM. There may also be a problem by this patch but I am not quite sure.
> > Edit: I decided to try, for once, disable all other sound hardware and run the game with 2 options, Realtek Speaker and Primary Sound Driver. Turns out, it work fine then.
> 
> Vanilla MM1 has problems selecting the right audio device. Try using Open1560, and if it is still broken left me know.

Yeah I agree. Those days Microsoft didn't expect us to have so many audio devices and thus the problem came.

**Closed** 2021-12-17 14:29 UTC
